version: '3.3'

services:
  centos-cpp:
    image: ziwiwiz/centos-cpp:2.0
    container_name: centos-cpp
    hostname: centos
    # user: billdev
    # working_dir: /home/billdev
    restart: always
    ports:
      - "22022:22"
    environment:
      TZ: Asia/Shanghai
    privileged: true
    stdin_open: true
    tty: true
